In the SQL portion of this project,
  we performed comprehensive data analysis on a sales dataset by writing and executing several important queries that provided meaningful business insights.
  We started by calculating the total revenue generated by each product category, 
  which allowed us to understand which categories contributed most to overall sales performance. 
  We also used aggregate functions such as SUM, AVG, MAX, and MIN to determine key performance metrics like total sales, average unit prices,
  and the highest and lowest sales values. Additionally, we grouped the data by time-based dimensions, like months, to analyze seasonal sales trends and identify which months were most profitable. 
  One of the key queries we included calculated the percentage contribution of each category to total revenue, giving us a clear breakdown of revenue distribution.
  We also performed filtering using WHERE clauses and used ORDER BY to sort data meaningfully. The analysis helped reveal patterns in customer purchasing behavior, product demand, and regional performance.
  Overall, the SQL analysis played a critical role in building the foundation for our data-driven insights across the project
